services:
  nginx:
    depends_on:
      perms:
        condition: service_completed_successfully
    healthcheck:
      interval: 10s
      retries: 5
      start_period: 30s
      test: curl --fail --silent http://localhost:80
      timeout: 10s
    image: nginx
    ports:
    - 8080:80
    volumes:
    - docker-volume-nginx:/mnt/directories/dir1
  perms:
    command:
    - 'echo "applying permissions..."

      chmod 777 /mnt/directories/dir1

      chmod 777 /mnt/directories/dir2

      sleep 10

      echo "Done applying permissions"

      exit 0

      '
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512m
    entrypoint:
    - bash
    - -c
    image: bash
    user: root
    volumes:
    - docker-volume-nginx:/mnt/directories/dir1
volumes:
  docker-volume-nginx: {}

