name: Unit Tests

on:
  pull_request:
    paths:
      - "library/**"

jobs:
  run-unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt install python3-pytest python3-pytest-mock -y

      - name: Run Tests
        run: |
          pytest library
